export const REGIONS = [
  "north-africa",
  "east-africa",
  "horn-of-africa",
  "west-africa",
  "southern-africa",
  "levant",
  "gulf",
  "caucasus",
  "mediterranean",
  "western-europe",
  "central-europe",
  "central-asia",
  "south-asia",
  "southeast-asia",
  "east-asia",
  "north-america",
  "mesoamerica",
  "caribbean",
  "andean",
  "south-atlantic",
] as const;

export type RegionCode = (typeof REGIONS)[number];

export const REGION_LABELS: Record<RegionCode, { en: string; de: string }> = {
  "north-africa": { en: "North Africa", de: "Nordafrika" },
  "east-africa": { en: "East Africa", de: "Ostafrika" },
  "horn-of-africa": { en: "Horn of Africa", de: "Horn von Afrika" },
  "west-africa": { en: "West Africa", de: "Westafrika" },
  "southern-africa": { en: "Southern Africa", de: "Südliches Afrika" },
  levant: { en: "Levant", de: "Levante" },
  gulf: { en: "Arabian Gulf", de: "Arabischer Golf" },
  caucasus: { en: "Caucasus", de: "Kaukasus" },
  mediterranean: { en: "Mediterranean", de: "Mittelmeer" },
  "western-europe": { en: "Western Europe", de: "Westeuropa" },
  "central-europe": { en: "Central Europe", de: "Mitteleuropa" },
  "central-asia": { en: "Central Asia", de: "Zentralasien" },
  "south-asia": { en: "South Asia", de: "Südasien" },
  "southeast-asia": { en: "Southeast Asia", de: "Südostasien" },
  "east-asia": { en: "East Asia", de: "Ostasien" },
  "north-america": { en: "North America", de: "Nordamerika" },
  mesoamerica: { en: "Mesoamerica", de: "Mesoamerika" },
  caribbean: { en: "Caribbean", de: "Karibik" },
  andean: { en: "Andean", de: "Andenraum" },
  "south-atlantic": { en: "South Atlantic", de: "Südatlantik" },
};

// Placeholder dot positions on a 0–100 abstract canvas (x = longitude-ish, y = latitude-ish).
// Exact positions will be refined when the SVG worldmap asset is designed.
export const DOT_POSITIONS: Record<RegionCode, { x: number; y: number }> = {
  "north-africa": { x: 47, y: 32 },
  "east-africa": { x: 54, y: 45 },
  "horn-of-africa": { x: 59, y: 40 },
  "west-africa": { x: 38, y: 43 },
  "southern-africa": { x: 52, y: 60 },
  levant: { x: 57, y: 30 },
  gulf: { x: 62, y: 35 },
  caucasus: { x: 60, y: 25 },
  mediterranean: { x: 50, y: 26 },
  "western-europe": { x: 44, y: 20 },
  "central-europe": { x: 49, y: 19 },
  "central-asia": { x: 67, y: 26 },
  "south-asia": { x: 68, y: 37 },
  "southeast-asia": { x: 78, y: 44 },
  "east-asia": { x: 80, y: 28 },
  "north-america": { x: 18, y: 22 },
  mesoamerica: { x: 18, y: 38 },
  caribbean: { x: 23, y: 37 },
  andean: { x: 22, y: 52 },
  "south-atlantic": { x: 27, y: 60 },
};
