// Generates `src/lib/worldmap-dots.ts` — the committed Layer-1 worldmap
// silhouette (see ADR 0021). Re-run by hand after tuning the boundary table in
// `src/lib/worldmap-generate.ts`, then commit the regenerated output.
//
//   node --experimental-strip-types scripts/gen-worldmap-dots.ts
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import {
  buildDots,
  parseStaticGrid,
  WORLDMAP_COLS,
  WORLDMAP_ROWS,
} from "../src/lib/worldmap-generate.ts";

const here = (p: string) => fileURLToPath(new URL(p, import.meta.url));

const html = readFileSync(here("../src/components/worldmap-static/index.html"), "utf8");
const dots = buildDots(parseStaticGrid(html));

const rows = dots.map((d) => `  [${d.col}, ${d.row}, ${JSON.stringify(d.regionId)}],`).join("\n");

const out = `// GENERATED by scripts/gen-worldmap-dots.ts — do not edit by hand.
// Re-run after tuning the boundary table in worldmap-generate.ts. See ADR 0021.
import type { RegionCode } from "./regions.ts";
import type { WorldmapDot } from "./worldmap-generate.ts";

export const WORLDMAP_COLS = ${WORLDMAP_COLS};
export const WORLDMAP_ROWS = ${WORLDMAP_ROWS};

// [col, row, regionId] — land dots only, row-major.
const RAW: Array<[number, number, RegionCode]> = [
${rows}
];

export const WORLDMAP_DOTS: WorldmapDot[] = RAW.map(([col, row, regionId]) => ({
  col,
  row,
  regionId,
}));
`;

writeFileSync(here("../src/lib/worldmap-dots.ts"), out);
console.log(`Wrote ${dots.length} dots to src/lib/worldmap-dots.ts`);
